using System.Reflection;
using System.Text;
using MigrationLibrary.Attributes;
using Npgsql;

namespace MigrationLibrary;

public class MigrationLibrary
{
    private readonly string _connectionString;

    public MigrationLibrary(string connectionString)
    {
        _connectionString = connectionString;
        
        InitMigrations();
    }

    private bool CheckIfMigrationsExist()
    {
        using (var dataSource = NpgsqlDataSource.Create(_connectionString))
        {
            string sql = "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = '_migrations')";
            var command = dataSource.CreateCommand(sql);

            return (bool)command.ExecuteScalar();
        }
    }
    
    private void InitMigrations()
    {
        if (!CheckIfMigrationsExist())
        {
            using (var dataSource = NpgsqlDataSource.Create(_connectionString))
            {
                var sqlQueryStringBuilder = new StringBuilder();
                sqlQueryStringBuilder.AppendLine("CREATE TABLE IF NOT EXISTS _migrations " +
                                                 "(id INT GENERATED BY DEFAULT AS IDENTITY, " +
                                                 "migration_name TEXT, applied_at TIMESTAMP, " +
                                                 "model_snapshot TEXT, up_sql TEXT, down_sql TEXT); ");
                var command = dataSource.CreateCommand(sqlQueryStringBuilder.ToString());
                command.ExecuteNonQuery();
            }
        }
    }
    
    public void CreateMigration()
    {
        var upSql = BuildSql();
        
        using (var dataSource = NpgsqlDataSource.Create(_connectionString))
        {
            var sqlQuery = "INSERT INTO _migrations (migration_name, applied_at, model_snapshot, up_sql, down_sql) " +
                           "VALUES (@migration_name, @applied_at, @model_snapshot, @up_sql, @down_sql)";
            var command = dataSource.CreateCommand(sqlQuery);
            
            command.Parameters.AddWithValue("@migration_name", "migrations");
            command.Parameters.AddWithValue("@applied_at", DateTime.Now);
            command.Parameters.AddWithValue("@model_snapshot", "test");
            command.Parameters.AddWithValue("@up_sql", upSql);
            command.Parameters.AddWithValue("@down_sql", "test");
            
            command.ExecuteNonQuery();
        }
    }

    public void ApplyMigration()
    {
        using (var dataSource = NpgsqlDataSource.Create(_connectionString))
        {
            string selectSql = "SELECT up_sql FROM _migrations ORDER BY id DESC LIMIT 1";

            try
            {
                using (var cmd = dataSource.CreateCommand(selectSql))
                {
                    var upSql = cmd.ExecuteScalar()?.ToString();

                    if (string.IsNullOrEmpty(upSql))
                    {
                        Console.WriteLine("Нет доступных миграций для применения.");
                        return;
                    }

                    using (var execCmd = dataSource.CreateCommand(upSql))
                    {
                        execCmd.ExecuteNonQuery();
                        Console.WriteLine("Миграция успешно применена.");
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Ошибка при применении миграции: {ex.Message}");
                throw;
            }
        }
    }
    
public Dictionary<string, IEnumerable<(string columnName, string columnType, bool isPrimaryKey)>> ParseSchemas()
{
    var assembly = Assembly.GetExecutingAssembly();

    var tables = assembly.GetTypes()
        .Where(type => type.IsClass && Attribute.IsDefined(type, typeof(TableAttribute)))
        .ToList();

    var map = new Dictionary<string, IEnumerable<(string, string, bool)>>();

    foreach (var table in tables)
    {
        var properties = table.GetProperties().Select(p => (
            columnName: p.GetCustomAttribute<ColumnAttribute>()?.ColumnName ?? p.Name,
            columnType: p.PropertyType.Name,
            isPrimaryKey: p.GetCustomAttribute<PrimaryKeyAttribute>() != null
        ));

        map.Add(table.GetCustomAttribute<TableAttribute>().TableName, properties);
    }

    return map;
}

private string BuildSql()
{
    var schemas = ParseSchemas();
    var sqlBuilder = new StringBuilder();

    foreach (var schema in schemas)
    {
        var tableName = schema.Key;
        var fields = schema.Value;

        // Создаем таблицу, если она не существует
        sqlBuilder.AppendLine($"CREATE TABLE IF NOT EXISTS \"{tableName}\" ();");

        // Обновляем структуру таблицы
        foreach (var (columnName, columnType, isPrimaryKey) in fields)
        {
            var pgType = isPrimaryKey ? (columnType == "Int64" ? "BIGINT" : "INTEGER") : MapCSharpTypeToPostgresType(columnType);
            var generatedClause = isPrimaryKey ? " GENERATED BY DEFAULT AS IDENTITY" : "";
            var primaryKeyConstraint = isPrimaryKey ? " PRIMARY KEY" : "";

            // Проверяем существование столбца и добавляем или обновляем
            sqlBuilder.AppendLine($"DO $$");
            sqlBuilder.AppendLine($"BEGIN");
            sqlBuilder.AppendLine($"    IF NOT EXISTS (SELECT FROM information_schema.columns WHERE table_name = '{tableName}' AND column_name = '{columnName}' AND table_schema = 'public') THEN");
            sqlBuilder.AppendLine($"        ALTER TABLE \"{tableName}\" ADD COLUMN \"{columnName}\" {pgType}{generatedClause}{primaryKeyConstraint};");
            sqlBuilder.AppendLine($"    ELSE");
            // Обновляем тип столбца, если он отличается (без GENERATED для существующих столбцов)
            sqlBuilder.AppendLine($"        IF (SELECT data_type FROM information_schema.columns WHERE table_name = '{tableName}' AND column_name = '{columnName}' AND table_schema = 'public') != '{pgType.ToLower()}' THEN");
            sqlBuilder.AppendLine($"            ALTER TABLE \"{tableName}\" ALTER COLUMN \"{columnName}\" SET DATA TYPE {pgType};");
            sqlBuilder.AppendLine($"        END IF;");
            if (isPrimaryKey)
            {
                // Проверяем, есть ли PRIMARY KEY, и добавляем, если нет
                sqlBuilder.AppendLine($"        IF NOT EXISTS (SELECT FROM information_schema.table_constraints WHERE table_name = '{tableName}' AND constraint_type = 'PRIMARY KEY' AND constraint_name = '{tableName}_pkey') THEN");
                sqlBuilder.AppendLine($"            ALTER TABLE \"{tableName}\" ADD CONSTRAINT \"{tableName}_pkey\" PRIMARY KEY (\"{columnName}\");");
                sqlBuilder.AppendLine($"        END IF;");
            }
            sqlBuilder.AppendLine($"    END IF;");
            sqlBuilder.AppendLine($"END $$;");
        }
        
        sqlBuilder.AppendLine($"DO $$");
        sqlBuilder.AppendLine($"DECLARE");
        sqlBuilder.AppendLine($"    col_name TEXT;");
        sqlBuilder.AppendLine($"BEGIN");
        sqlBuilder.AppendLine($"    FOR col_name IN (SELECT column_name FROM information_schema.columns WHERE table_name = '{tableName}' AND table_schema = 'public' AND column_name NOT IN ({string.Join(", ", fields.Select(f => $"'{f.columnName}'"))})) LOOP");
        sqlBuilder.AppendLine($"        EXECUTE 'ALTER TABLE \"' || '{tableName}' || '\" DROP COLUMN \"' || col_name || '\";';");
        sqlBuilder.AppendLine($"    END LOOP;");
        sqlBuilder.AppendLine($"END $$;");

        sqlBuilder.AppendLine();
    }

    return sqlBuilder.ToString().TrimEnd();
}
    
    private string MapCSharpTypeToPostgresType(string csharpType)
    {
        return csharpType switch
        {
            "String" => "TEXT",
            "Int32" => "INTEGER",
            _ => throw new NotSupportedException($"Type {csharpType} is not mapped to a PostgreSQL type.")
        };
    }
}